# Generated by Django 4.2.16 on 2024-09-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_reco", "0003_song_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="song", name="likes", field=models.IntegerField(default=0),
        ),
    ]
